/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TSilva
 */
public class FormLibraryMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormLibraryMenu
     */
    public FormLibraryMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Library_Booking = new javax.swing.JButton();
        btn_Fine_Payment = new javax.swing.JButton();
        btn_View_Loan_History = new javax.swing.JButton();
        btn_View_Total_Fine_Paid = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Library_Booking.setText("Library Booking");
        btn_Library_Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Library_BookingActionPerformed(evt);
            }
        });

        btn_Fine_Payment.setText("Fine payments");
        btn_Fine_Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Fine_PaymentActionPerformed(evt);
            }
        });

        btn_View_Loan_History.setText("View Loan History");
        btn_View_Loan_History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_View_Loan_HistoryActionPerformed(evt);
            }
        });

        btn_View_Total_Fine_Paid.setText("View Total Fine Paid");
        btn_View_Total_Fine_Paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_View_Total_Fine_PaidActionPerformed(evt);
            }
        });

        btn_Exit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_View_Loan_History, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(btn_Library_Booking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_View_Total_Fine_Paid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Fine_Payment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Library_Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Fine_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_View_Loan_History, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_View_Total_Fine_Paid, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Library_BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Library_BookingActionPerformed
        // TODO add your handling code here:
        FormLibraryBooking formLibraryBooking = new FormLibraryBooking();
        formLibraryBooking.setVisible(true);
    }//GEN-LAST:event_btn_Library_BookingActionPerformed

    private void btn_Fine_PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Fine_PaymentActionPerformed
        // TODO add your handling code here:
        FormLibraryFinePayments formLibraryFinePayment = new FormLibraryFinePayments();
        formLibraryFinePayment.setVisible(true);
    }//GEN-LAST:event_btn_Fine_PaymentActionPerformed

    private void btn_View_Loan_HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_View_Loan_HistoryActionPerformed
        // TODO add your handling code here:
        FormViewLoanHistory formViewLoanHistory = new FormViewLoanHistory();
        formViewLoanHistory.setVisible(true);
    }//GEN-LAST:event_btn_View_Loan_HistoryActionPerformed

    private void btn_View_Total_Fine_PaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_View_Total_Fine_PaidActionPerformed
        // TODO add your handling code here:
        FormViewTotalFinePaid formViewTotalFinePaid = new FormViewTotalFinePaid();
        formViewTotalFinePaid.setVisible(true);
    }//GEN-LAST:event_btn_View_Total_Fine_PaidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLibraryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLibraryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLibraryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLibraryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLibraryMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Fine_Payment;
    private javax.swing.JButton btn_Library_Booking;
    private javax.swing.JButton btn_View_Loan_History;
    private javax.swing.JButton btn_View_Total_Fine_Paid;
    // End of variables declaration//GEN-END:variables
}
