import java.util.ArrayList;

import ct6013librarysystem.*;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TSilva
 */
public class FormLibraryFinePayments extends javax.swing.JFrame {
    ArrayList<Document> lstLoans = new ArrayList<>();
    /**
     * Creates new form LibraryFinePayments
     */
    public FormLibraryFinePayments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBooking_Loan_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFine_Id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCopy_ID = new javax.swing.JTextField();
        btnCheck_Fine = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoanList = new javax.swing.JTable();
        btnPay_Fine = new javax.swing.JButton();
        btnCheck_Booking = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtStudent_Number = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFineList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Booking Loan ID");

        jLabel2.setText("Fine ID");

        txtFine_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFine_IdActionPerformed(evt);
            }
        });

        jLabel3.setText("Copy ID");

        btnCheck_Fine.setText("Check Fine");
        btnCheck_Fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheck_FineActionPerformed(evt);
            }
        });

        tblLoanList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking Loan ID", "Copy ID", "Start Loan Date", "Expected Return Date", "Actual Return Date"
            }
        ));
        jScrollPane1.setViewportView(tblLoanList);

        btnPay_Fine.setText(" Pay Fine");
        btnPay_Fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPay_FineActionPerformed(evt);
            }
        });

        btnCheck_Booking.setText("Check Booking");
        btnCheck_Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheck_BookingActionPerformed(evt);
            }
        });

        jLabel6.setText("Student Number");

        tblFineList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fine ID", "Book Overdue", "Total Fine", "Fine Paid"
            }
        ));
        jScrollPane2.setViewportView(tblFineList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtStudent_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtBooking_Loan_ID)
                                            .addComponent(txtFine_Id)
                                            .addComponent(txtCopy_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCheck_Booking)
                                    .addComponent(btnCheck_Fine)))
                            .addComponent(btnPay_Fine))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtFine_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtStudent_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck_Booking))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBooking_Loan_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCopy_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck_Fine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPay_Fine)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFine_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFine_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFine_IdActionPerformed

    private void btnCheck_BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheck_BookingActionPerformed
        // TODO add your handling code here:
        CT6013LibrarySystem ct6013LibrarySystem = new CT6013LibrarySystem();
        
        // checkLoan gets data about the fine and loan table using the fine_id and student_number values as a search criteria
        // through the Oracle database
        Document loanBooking = ct6013LibrarySystem.checkLoan(txtFine_Id.getText(), txtStudent_Number.getText());
        
        //Adding data into GUI table
        DefaultTableModel tbl_model_loan_list = (DefaultTableModel) tblLoanList.getModel();
        tbl_model_loan_list.addRow(new Object[]{loanBooking.get("Booking_Loan_ID"), loanBooking.get("Copy_ID"), loanBooking.get("Start_Loan_Date"), loanBooking.get("Expected_Return_Date"), loanBooking.get("Actual_Return_Date")});
        // The defaultTableModel allow the data gathered from the loan and fine table to be put into a document for
        // tblLoanList to display
        
        //Adding data into a list variable to be used when payment button pressed
        lstLoans.add(loanBooking);
    }//GEN-LAST:event_btnCheck_BookingActionPerformed

    private void btnCheck_FineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheck_FineActionPerformed
        // TODO add your handling code here:
        CT6013LibrarySystem ct6013LibrarySystem = new CT6013LibrarySystem();
        
        Document fineTable = ct6013LibrarySystem.getFineInfo(txtFine_Id.getText(), txtBooking_Loan_ID.getText(), txtCopy_ID.getText());
        // getFineInfo gets data about the fine table using the fine_id, copy_id and book_loan_id values as a search criteria
        // through the Oracle database        
        
        //Adding data into GUI table
        DefaultTableModel tbl_model_loan_list = (DefaultTableModel) tblFineList.getModel();
        tbl_model_loan_list.addRow(new Object[]{fineTable.get("Fine_ID"), fineTable.get("Book_Overdue"), fineTable.get("Total_Fine"), fineTable.get("Fine_Paid")});
        // The defaultTableModel allow the data gathered from the fine table to be put into a document for
        // tblFineList to display 
        
        //Adding data into a list variable to be used when fine button pressed
        lstLoans.add(fineTable);
        
    
    }//GEN-LAST:event_btnCheck_FineActionPerformed

    
    
    
    private void btnPay_FineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPay_FineActionPerformed
        // TODO add your handling code here:
        CT6013LibrarySystem ct6013LibrarySystem = new CT6013LibrarySystem();
        
                
        Document payFine = new Document()
            .append("Fine_ID", txtFine_Id.getText())
            .append("Student_Number", txtStudent_Number.getText())
            .append("Booking_Loan_ID", txtBooking_Loan_ID.getText())
            .append("Copy_ID", txtCopy_ID.getText());
        // Makes document called payFine containing values called from the Text Fields in the form    
        
        // Line 238 - 239 uses the payFine document provide values to trigger the sql update statement while using
        // the values the the text fields and passing on in the payFine document
        payFine.append("Paying", lstLoans);
        ct6013LibrarySystem.finePayment(payFine);
        // Returns text when the finePayment code from CT6013LibrarySystems.java is successful
        JOptionPane.showMessageDialog(this, "Payment has been succesfully made");
        
    }//GEN-LAST:event_btnPay_FineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLibraryFinePayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLibraryFinePayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLibraryFinePayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLibraryFinePayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLibraryFinePayments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck_Booking;
    private javax.swing.JButton btnCheck_Fine;
    private javax.swing.JButton btnPay_Fine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFineList;
    private javax.swing.JTable tblLoanList;
    private javax.swing.JTextField txtBooking_Loan_ID;
    private javax.swing.JTextField txtCopy_ID;
    private javax.swing.JTextField txtFine_Id;
    private javax.swing.JTextField txtStudent_Number;
    // End of variables declaration//GEN-END:variables
}
