
import ct6013librarysystem.CT6013LibrarySystem;
import java.util.ArrayList;
import java.util.Iterator;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TSilva
 */

public class FormViewLoanHistory extends javax.swing.JFrame {

    /**
     * Creates new form FormViewLoanHistory
     */
    public FormViewLoanHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoan_History = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtStudent_Number = new javax.swing.JTextField();
        btnShow_History = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLoan_History = new javax.swing.JTextArea();
        fromBookingDate = new org.jdesktop.swingx.JXDatePicker();
        toBookingDate = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLoan_History.setText("Loan History");

        jLabel1.setText("Student Number");

        jLabel2.setText("From Date");

        jLabel3.setText("To Date");

        btnShow_History.setText("Show History");
        btnShow_History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShow_HistoryActionPerformed(evt);
            }
        });

        txtLoan_History.setColumns(20);
        txtLoan_History.setRows(5);
        jScrollPane1.setViewportView(txtLoan_History);

        fromBookingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromBookingDateActionPerformed(evt);
            }
        });

        toBookingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBookingDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLoan_History, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(286, 286, 286))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShow_History)
                            .addComponent(txtStudent_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoan_History, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStudent_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fromBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(toBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShow_History)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromBookingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromBookingDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromBookingDateActionPerformed

    private void toBookingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBookingDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toBookingDateActionPerformed

    private void btnShow_HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShow_HistoryActionPerformed
        // TODO add your handling code here:
        CT6013LibrarySystem ct6013LibrarySystem = new CT6013LibrarySystem();
        ArrayList<Document> colHistory = ct6013LibrarySystem.getBookLoanHistory(fromBookingDate.getDate(), toBookingDate.getDate(), txtStudent_Number.getText());
        // The arrayList is getting the Book Loan History from the Loan table that getBookLoanHistory is collecting between the
        // date between the  value that fromBookingDate and toBookingDate gives with the assigned/related Student Number
        
        // Line 150 - 160 is running a String called prettyPrint which tells the application what to print in the text area
        // for txt_Loan_History while using the data gather from getBookLoanHistory which is found in CT6013LibrarySystems.java
        Iterator<Document> cursor = colHistory.iterator();
        String result = "";
        try {
          while (cursor.hasNext()) {
            Document doc = cursor.next();

            result = result + prettyPrint(doc) + "\n";
          }
        } finally {
          
        }
        
        txtLoan_History.setText(result);
        // Generates the text for the students loan history within the text area called txt_Loan_History using result  
        
    }//GEN-LAST:event_btnShow_HistoryActionPerformed

    
    
    
    public String prettyPrint(Document docInv) {
        String prettyInv = "";
        try {
            prettyInv = "";
            prettyInv = prettyInv + "Booking Loan ID : " + docInv.get("Booking_Loan_ID") + "\n";
            prettyInv = prettyInv + "Copy ID : " + docInv.get("Copy_ID") + "\n";
            prettyInv = prettyInv + "Student Number : " + docInv.get("Student_Number") + "\n";
            prettyInv = prettyInv + "First Name : " + docInv.get("First_Name") + "\n";
            prettyInv = prettyInv + "Last Name : " + docInv.get("Last_Name") + "\n";
            prettyInv = prettyInv + "Date Of Birth : " + docInv.get("Date_Of_Birth") + "\n";
            prettyInv = prettyInv + "City : " + docInv.get("City") + "\n";
            prettyInv = prettyInv + "Postcode : " + docInv.get("Postcode") + "\n";
            prettyInv = prettyInv + "Start Loan Date : " + docInv.get("Start_Loan_Date") + "\n";
            prettyInv = prettyInv + "\n\n";            
            prettyInv = prettyInv + "Book ID \t ISBN \t Title \t Copy Number \t Author ID\n";
            prettyInv = prettyInv + "----------------------------------------------------------------------------------------------------------------\n";
            // PrettyPrint is giving instructions to give a list of words in a certain structure along with the values
            // next to them using the field name from the database tables to get the data 
            
            ArrayList invItemList = (ArrayList) docInv.get("Book_Loan_List");
    
            Iterator itr = invItemList.iterator();
            Document docBook;
            while(itr.hasNext()){
                docBook = (Document)itr.next();
                prettyInv = prettyInv + docBook.get("Book_ID") + "\t"; 
                prettyInv = prettyInv + docBook.get("ISBN") + "\t"; 
                prettyInv = prettyInv + docBook.get("Title") + "\t"; 
                prettyInv = prettyInv + docBook.get("Copy_Number") + "\t"; 
                prettyInv = prettyInv + docBook.get("Author_ID") + "\t";
            } 
            // docBook is get another layer for the report which will with out another set of data which will contain
            // details about the book which have been recorded under the book loan
        } catch (NullPointerException npe) {
            prettyInv = "Book not found.";
        }
        return prettyInv;
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormViewLoanHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormViewLoanHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormViewLoanHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormViewLoanHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormViewLoanHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow_History;
    private org.jdesktop.swingx.JXDatePicker fromBookingDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoan_History;
    private org.jdesktop.swingx.JXDatePicker toBookingDate;
    private javax.swing.JTextArea txtLoan_History;
    private javax.swing.JTextField txtStudent_Number;
    // End of variables declaration//GEN-END:variables
}
