
   import java.util.ArrayList;

import ct6013librarysystem.*;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TSilva
 */
public class FormLibraryBooking extends javax.swing.JFrame {
    ArrayList<Document> lstBooks = new ArrayList<>();

    /**
     * Creates new form FormLibraryBooking
     */
    public FormLibraryBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBooking_Loan_ID = new javax.swing.JLabel();
        lblStudent_Number = new javax.swing.JLabel();
        lblCopy_ID = new javax.swing.JLabel();
        txtBooking_Loan_ID = new javax.swing.JTextField();
        txtStudent_Number = new javax.swing.JTextField();
        txtCopy_ID = new javax.swing.JTextField();
        btnCheck_Booking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookList = new javax.swing.JTable();
        btnConfirm_Booking = new javax.swing.JButton();
        btn_Return_Book = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFine_ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBooking_Loan_ID.setText("Booking Loan ID");

        lblStudent_Number.setText("Student Number");

        lblCopy_ID.setText("Copy ID");

        txtBooking_Loan_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBooking_Loan_IDActionPerformed(evt);
            }
        });

        btnCheck_Booking.setText("Check book");
        btnCheck_Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheck_BookingActionPerformed(evt);
            }
        });

        tblBookList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Copy ID", "Book ID", "ISBN", "Title", "Copy Number", "Author ID"
            }
        ));
        jScrollPane1.setViewportView(tblBookList);

        btnConfirm_Booking.setText("Confirm Booking");
        btnConfirm_Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirm_BookingActionPerformed(evt);
            }
        });

        btn_Return_Book.setText("Return Book");
        btn_Return_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Return_BookActionPerformed(evt);
            }
        });

        jLabel2.setText("Fine ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCopy_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStudent_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(lblBooking_Loan_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBooking_Loan_ID)
                                    .addComponent(txtStudent_Number)
                                    .addComponent(txtCopy_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnCheck_Booking))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFine_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Return_Book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConfirm_Booking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBooking_Loan_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtBooking_Loan_ID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudent_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudent_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCopy_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCopy_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCheck_Booking)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm_Booking)
                    .addComponent(jLabel2)
                    .addComponent(txtFine_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Return_Book)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBooking_Loan_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBooking_Loan_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBooking_Loan_IDActionPerformed

    private void btnCheck_BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheck_BookingActionPerformed
        // TODO add your handling code here:
        CT6013LibrarySystem ct6013LibrarySystem = new CT6013LibrarySystem();
        Document book = ct6013LibrarySystem.getBook(txtCopy_ID.getText());
        // getBook gets data about the books and the copy_id through the Oracle database and searching by using the dates
        // provided by txtCopy_ID which is related to the book table
        
        book.append("Copy_ID", Double.parseDouble(txtCopy_ID.getText()));
        book.remove("");
        
        //Adding data into GUI table
        DefaultTableModel tbl_model_book_list = (DefaultTableModel) tblBookList.getModel();
        tbl_model_book_list.addRow(new Object[]{book.get("Copy_ID"),book.get("Book_ID"), book.get("ISBN"), book.get("Title"), book.get("Copy_Number"), book.get("Author_ID")});
        // The defaultTableModel allow the data gathered from the book and copy table to be put into a document for
        // tblBookList to display
        
        //Adding data into a list variable to be used when booking button pressed
        lstBooks.add(book);
    }//GEN-LAST:event_btnCheck_BookingActionPerformed

    private void btn_Return_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Return_BookActionPerformed
        // TODO add your handling code here:
        CT6013LibrarySystem ct6013LibrarySystem = new CT6013LibrarySystem();
        
                
        Document returning = new Document()
            .append("Copy_ID", txtBooking_Loan_ID.getText())
            .append("Booking_Loan_ID", txtBooking_Loan_ID.getText())
            .append("Copy_ID", txtCopy_ID.getText())
            .append("Student_Number", txtStudent_Number.getText())
            .append("Fine_ID", txtFine_ID.getText());
        // Makes document called returning containing values called from the Text Fields in the form
        
        // Line 205 - 206 uses the returning document provide values to trigger an update query         
        returning.append("FineUpdate", lstBooks);
        ct6013LibrarySystem.returningBook(returning);
        // Returns text when the FineUpdate code from CT6013LibrarySystems.java is successful
        JOptionPane.showMessageDialog(this, "Book has been succesfully returned");
    }//GEN-LAST:event_btn_Return_BookActionPerformed

    private void btnConfirm_BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirm_BookingActionPerformed
        // TODO add your handling code here:
        CT6013LibrarySystem ct6013LibrarySystem = new CT6013LibrarySystem();
        
               
                
        Document booking = new Document() 
            .append("Booking_Loan_ID", txtBooking_Loan_ID.getText())
            .append("Copy_ID", txtCopy_ID.getText())
            .append("Student_Number", txtStudent_Number.getText())
            .append("Fine_ID", txtFine_ID.getText());
        // Makes document called booking containing values called from the Text Fields in the form    
        
        // Line 226 - 227 uses the booking document provide values to trigger a sql statement to make a new record
        // for the loan table
        booking.append("Fine", lstBooks);
        ct6013LibrarySystem.createBooking(booking);
        // Returns text when the createBooking code from CT6013LibrarySystems.java is successful
        JOptionPane.showMessageDialog(this, "Booking has created succesfully");
        
    }//GEN-LAST:event_btnConfirm_BookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLibraryBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLibraryBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLibraryBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLibraryBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLibraryBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck_Booking;
    private javax.swing.JButton btnConfirm_Booking;
    private javax.swing.JButton btn_Return_Book;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBooking_Loan_ID;
    private javax.swing.JLabel lblCopy_ID;
    private javax.swing.JLabel lblStudent_Number;
    private javax.swing.JTable tblBookList;
    private javax.swing.JTextField txtBooking_Loan_ID;
    private javax.swing.JTextField txtCopy_ID;
    private javax.swing.JTextField txtFine_ID;
    private javax.swing.JTextField txtStudent_Number;
    // End of variables declaration//GEN-END:variables
}
