DELETE FROM TBL_AUTHOR;

INSERT INTO TBL_AUTHOR (AUTHOR_ID, FIRST_NAME, LAST_NAME)
VALUES ('AID0001', 'Silva', 'Red');
    
INSERT INTO TBL_AUTHOR (AUTHOR_ID, FIRST_NAME, LAST_NAME)
VALUES ('AID0002', 'Bazer', 'Blue');
    
INSERT INTO TBL_AUTHOR (AUTHOR_ID, FIRST_NAME, LAST_NAME)
VALUES ('AID0003', 'Amy', 'Yellow');
    
INSERT INTO TBL_AUTHOR (AUTHOR_ID, FIRST_NAME, LAST_NAME)
VALUES ('AID0004', 'Simon', 'Silver');